### ISSUE TITLE
mysql 连接失败 mac 版 2.0.2

### ISSUE THREAD

**Issue by hyccgit** [SafeGroceryStore/MDUT#12]
![image](https://user-images.githubusercontent.com/24220639/120963596-719af500-c794-11eb-9c87-ab7c3b4297db.png)
java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at Dao.MysqlDao.<init>(MysqlDao.java:73)
	at Controller.MysqlController.lambda$initialize$2(MysqlController.java:93)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Ch1ngg** [comment]
jar 包依赖没有加载进内存，请检查配置文件。希望下次可以按照格式填写 ISSUE 喔 ：）
