### ISSUE TITLE
走socks5以后数据库报错

### ISSUE THREAD

**Issue by Alberthchang** [SafeGroceryStore/MDUT#36]
## 系统环境
 - OS: Win 10 x64
 - JavaVersion 1.8

## 软件版本
 - Version 2.0.7

## Bug 详细描述
java.lang.ClassNotFoundException: oracle.jdbc.driver.OracleDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at Dao.OracleDao.<init>(OracleDao.java:67)
	at Controller.OracleController.lambda$initialize$2(OracleController.java:199)
	at java.lang.Thread.run(Thread.java:748)

报错信息
![image](https://user-images.githubusercontent.com/17517153/150554917-21d928d8-15c2-4b2a-889f-45cf4d023e88.png)

我是从内网zou走socks5代理，所有的数据库都会报错

**Comment by Ch1ngg** [comment]
#12
