### ISSUE TITLE
Not on FX application thread; currentThread = Thread-7

### ISSUE THREAD

**Issue by DeEpinGh0st** [SafeGroceryStore/MDUT#45]
数据库连接后，执行命令报如下错误
```
Exception in thread "Thread-7" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-7
        at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
        at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
        at javafx.stage.Stage.<init>(Stage.java:241)
        at javafx.stage.Stage.<init>(Stage.java:227)
        at javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
        at javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
        at javafx.scene.control.Dialog.<init>(Dialog.java:263)
        at javafx.scene.control.Alert.<init>(Alert.java:245)
        at javafx.scene.control.Alert.<init>(Alert.java:223)
        at Util.MessageUtil.showErrorMessage(MessageUtil.java:58)
        at Controller.RedisController.lambda$redisEvalCommand$8(RedisController.java:177)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by Ch1ngg** [comment]
使用文档看了吗？连啥数据库报错。怎么触发的报错？数据库版本是多少？这种线程报错我无法知道原因去排查

在 2022年5月27日，09:28，S0cke3t ***@***.***> 写道：

﻿

数据库连接后，执行命令报如下错误

Exception in thread "Thread-7" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-7
        at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
        at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
        at javafx.stage.Stage.<init>(Stage.java:241)
        at javafx.stage.Stage.<init>(Stage.java:227)
        at javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
        at javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
        at javafx.scene.control.Dialog.<init>(Dialog.java:263)
        at javafx.scene.control.Alert.<init>(Alert.java:245)
        at javafx.scene.control.Alert.<init>(Alert.java:223)
        at Util.MessageUtil.showErrorMessage(MessageUtil.java:58)
        at Controller.RedisController.lambda$redisEvalCommand$8(RedisController.java:177)
        at java.lang.Thread.run(Thread.java:745)

**Comment by DeEpinGh0st** [comment]
> 使用文档看了吗？连啥数据库报错。怎么触发的报错？数据库版本是多少？这种线程报错我无法知道原因去排查 在 2022年5月27日，09:28，S0cke3t ***@***.***> 写道： ﻿ 数据库连接后，执行命令报如下错误 Exception in thread "Thread-7" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-7 at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236) at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423) at javafx.stage.Stage.<init>(Stage.java:241) at javafx.stage.Stage.<init>(Stage.java:227) at javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52) at javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52) at javafx.scene.control.Dialog.<init>(Dialog.java:263) at javafx.scene.control.Alert.<init>(Alert.java:245) at javafx.scene.control.Alert.<init>(Alert.java:223) at Util.MessageUtil.showErrorMessage(MessageUtil.java:58) at Controller.RedisController.lambda$redisEvalCommand$8(RedisController.java:177) at java.lang.Thread.run(Thread.java:745) — Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSafeGroceryStore%2FMDUT%2Fissues%2F45&data=05%7C01%7C%7Cbbfb19e288bd42fa03f808da3f802541%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637892116866902886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Dt6rn6ZPf11md5NMGK04FeLQDxwlJtS%2BbyFcs8qkOa4%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEI6FPJZHRBPAORO2OFW6Z3VMAQKHANCNFSM5XC2EB3Q&data=05%7C01%7C%7Cbbfb19e288bd42fa03f808da3f802541%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637892116866902886%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HAUcQM%2ByB2D9As9%2BX2FWNikuPV3pIpv3qEyIQRUoKQY%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

正常连接redis,并设置主从同步后.输入命令点击执行后报如上错误
环境
Windows 10 Pro 21H2 x64
Redis: 4.0.14 docker部署
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by Ch1ngg** [comment]
Windows 部署的 Redis吗

**Comment by Ch1ngg** [comment]
Redis 4.0.14 的 Docker pull命令和启动命令能发一下吗，我这边测试一下

**Comment by DeEpinGh0st** [comment]
> Redis 4.0.14 的 Docker pull命令和启动命令能发一下吗，我这边测试一下

Linux下跑的Docker
Redis容器用的vulhub/redis:4.0.14
使用Portainer部署
![](https://i.bmp.ovh/imgs/2022/05/27/126e3e4e8941fc4a.png)

**Comment by Ch1ngg** [comment]
暂时没有空。我抽时间复现一下

**Comment by Ch1ngg** [comment]
Docker环境问题。本地虚拟机搭建环境测试成功提权，无错误
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/17949373/171988745-8fa608d7-7f3a-4045-b363-e97fc8ccd0f4.png">
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/17949373/171988754-919ab122-a0e0-4cff-90b4-b71ff0e9580f.png">
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/17949373/171988761-db31031c-2f3f-4989-8f19-af0ae89e53f2.png">

**Comment by jinmingyong** [comment]
大佬我windows下 mysql、redis 执行命令都会报这个错
Exception in thread "Thread-7" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-7
        at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:281)
        at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:445)
        at javafx.stage.Stage.<init>(Stage.java:241)
        at javafx.stage.Stage.<init>(Stage.java:227)
        at javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
        at javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
        at javafx.scene.control.Dialog.<init>(Dialog.java:263)
        at javafx.scene.control.Alert.<init>(Alert.java:245)
        at javafx.scene.control.Alert.<init>(Alert.java:223)
        at Util.MessageUtil.showExceptionMessage(MessageUtil.java:24)
        at Dao.RedisDao.eval(RedisDao.java:180)
        at Controller.RedisController.lambda$redisEvalCommand$8(RedisController.java:180)
        at java.lang.Thread.run(Unknown Source)
