### ISSUE TITLE
v2.0.8这个版本呢，我用最新的版本连接要报错

### ISSUE THREAD

**Issue by acvxd** [SafeGroceryStore/MDUT#57]
![image](https://user-images.githubusercontent.com/42563302/209455210-9003f8ea-7f91-4b31-af22-923dde4396bf.png)

java.lang.ClassNotFoundException: net.sourceforge.jtds.jdbc.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at Dao.MssqlDao.<init>(MssqlDao.java:58)
	at Controller.AddAndEditController.lambda$TestConnectAction$14(AddAndEditController.java:354)
	at java.lang.Thread.run(Thread.java:750)

**Comment by shushu-12** [comment]
我一直在哭，去年还能用今年就驱动报错了

**Comment by shushu-12** [comment]
解决了，之前迁移环境的时候有个有个路径更改了但是mdut还是老路径




lijiasheng
***@***.***
