### ISSUE TITLE
连接MySQL jdbc时出现报错

### ISSUE THREAD

**Issue by interesthacker** [SafeGroceryStore/MDUT#77]
java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at Dao.MysqlDao.<init>(MysqlDao.java:73)
	at Controller.AddAndEditController.lambda$TestConnectAction$4(AddAndEditController.java:277)
	at java.lang.Thread.run(Thread.java:748)

**Comment by KudoShinichi-Jimmly** [comment]
我也是

**Comment by interesthacker** [comment]
将配置文件初始化就可以了 他有个bug 有时候会自动删掉那个驱动 导致链接不了的




风淡云轻
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SafeGroceryStore/MDUT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月26日(星期三) 中午11:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SafeGroceryStore/MDUT] 连接MySQL jdbc时出现报错 (Issue #77)





 
我也是

**Comment by Gaoda010101** [comment]
怎么修复？？？

**Comment by wsYu9a** [comment]
低版本数据库连接不了啊！！

**Comment by wsYu9a** [comment]
![Uploading image.png…]()
